# ambiguous grammar



number = number + number
       | number - number
       | number * number
       | number / number
       | number % number
       | number ^ number
       | (number) number
       | (number)



bool = number = number;
     | number > number;
     | number < number;
     | number >= number;
     | number <= number;

quantity = number, unit;
         | unit, number;


unit =
